/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpsgame;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author matthewbelgre
 */
public class RPSGUI extends javax.swing.JFrame {

    /**
     * Creates new form RPSGUI
     */
    public RPSGUI() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ButtonGroup group = new ButtonGroup();
        this.setLayout(null);
        initComponents();
        group.add(rock);
        group.add(scissors);
        group.add(paper);
        group.add(random);
        mainPanel.setBorder(BorderFactory.createEmptyBorder(0, 10, 10, 10));

//         ImageIcon icon = new ImageIcon("/Users/matthewbelgre/NetBeansProjects/RPSgame/src/rpsgame/rockLeft.jpeg");
//         Image newImage = icon.getScaledInstance(100, 100, Image.SCALE_DEFAULT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        //ImageIcon imageIcon = new ImageIcon("/Users/matthewbelgre/NetBeansProjects/RPSgame/src/rpsgame/rockLeft.jpeg"); // load the image to a imageIcon
        //Image image = imageIcon.getImage(); // transform it
        //Image newimg = image.getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        //imageIcon = new ImageIcon(newimg);
        leftImg =  new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        rightImg = new javax.swing.JLabel();
        winner = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rock = new javax.swing.JRadioButton();
        paper = new javax.swing.JRadioButton();
        scissors = new javax.swing.JRadioButton();
        random = new javax.swing.JRadioButton();
        play = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        leftLabel = new javax.swing.JLabel();
        rightLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Rock, Paper, Scissors!");

        jLabel3.setText("Make your move!");

        jLabel4.setText("Enter your name: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(331, 0, 462, 139);

        mainPanel.setVisible(true);
        mainPanel.setLayout(null);

        leftImg.setText(null);

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel5))
                    .addGroup(leftLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(leftImg, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(leftImg)
                .addGap(159, 159, 159)
                .addComponent(jLabel5)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mainPanel.add(left);
        left.setBounds(6, 6, 420, 218);

        rightImg.setText(null);

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(rightImg)
                .addGap(165, 165, 165))
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rightImg)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        mainPanel.add(right);
        right.setBounds(481, 6, 410, 218);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(140, 200, 1041, 250);

        winner.setText(null);
        winner.setFont(new Font("Serif", Font.PLAIN, 20));
        getContentPane().add(winner);
        winner.setBounds(504, 157, 160, 16);

        rock.setText("Rock");

        paper.setText("Paper");

        scissors.setText("Scissors");

        random.setText("Random");

        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setText("Pick your hand or choose random");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rock)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paper)
                            .addComponent(play))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(scissors)
                                .addGap(18, 18, 18)
                                .addComponent(random))
                            .addComponent(clear))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rock)
                    .addComponent(paper)
                    .addComponent(scissors)
                    .addComponent(random))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(play)
                    .addComponent(clear))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(340, 540, 462, 141);

        leftLabel.setText(null);
        leftLabel.setFont(new Font("Serif", Font.PLAIN, 16));
        getContentPane().add(leftLabel);
        leftLabel.setBounds(240, 480, 230, 16);

        rightLabel.setText(null);
        rightLabel.setFont(new Font("Serif", Font.PLAIN, 16));
        getContentPane().add(rightLabel);
        rightLabel.setBounds(720, 480, 220, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        String playerName = "";
        String str = name.getText();
        boolean flag = true;
        if (name.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a name to play");
         }else{

        
        try{
          playerName = str.substring(0, 1).toUpperCase() + str.substring(1);
          flag = false;
         }catch(StringIndexOutOfBoundsException e){
                      
          }
        Player computer = new Player("Computer");
        
        if (rock.isSelected()) {

            leftImg.setIcon(Player.ImageSelection(1));
            leftLabel.setText(playerName + " plays Rock");
            Player user = new Player(playerName, 1);
            int choice = computer.makeHandshape() + 3;
            rightImg.setIcon(Player.ImageSelection(choice));
            rightLabel.setText("Computer plays " + computer.getShape());
            winner.setText(Player.findWinner(user, computer) + " wins!!!!!");

        } else if (scissors.isSelected()) {

            leftImg.setIcon(Player.ImageSelection(2));
            leftLabel.setText(playerName + " plays Scissors");
            Player user = new Player(playerName, 2);
            int choice = computer.makeHandshape() + 3;
            rightImg.setIcon(Player.ImageSelection(choice));
            rightLabel.setText("Computer plays " + computer.getShape());
            winner.setText(Player.findWinner(user, computer) + " wins!!!!!");
        } else if (paper.isSelected()) {

            leftImg.setIcon(Player.ImageSelection(3));
            leftLabel.setText(playerName + " plays Paper");
            Player user = new Player(playerName, 3);
            int choice = computer.makeHandshape() + 3;
            rightImg.setIcon(Player.ImageSelection(choice));
            rightLabel.setText("Computer plays " + computer.getShape());
            winner.setText(Player.findWinner(user, computer) + " wins!!!!!");
        } else if (random.isSelected()) {
            Player user = new Player(playerName);
            int userChoice = user.makeHandshape();
            leftImg.setIcon(Player.ImageSelection(userChoice));
            leftLabel.setText(playerName + " plays " + user.getShape());
            int choice = computer.makeHandshape() + 3;
            rightImg.setIcon(Player.ImageSelection(choice));
            rightLabel.setText("Computer plays " + computer.getShape());
            winner.setText(Player.findWinner(user, computer) + " wins!!!!!");
        } else {
            JOptionPane.showMessageDialog(null, "Please choose a hand before you play");
        }
        }

    }//GEN-LAST:event_playActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        name.setText("");
        leftImg.setIcon(null);
        leftLabel.setText("");
        name.setText("");
        rightImg.setIcon(null);
        rightLabel.setText("");
        rock.setSelected(false);
        scissors.setSelected(false);
        paper.setSelected(false);
        random.setSelected(false);
        winner.setText("");
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel left;
    private javax.swing.JLabel leftImg;
    private javax.swing.JLabel leftLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton paper;
    private javax.swing.JButton play;
    private javax.swing.JRadioButton random;
    private javax.swing.JPanel right;
    private javax.swing.JLabel rightImg;
    private javax.swing.JLabel rightLabel;
    private javax.swing.JRadioButton rock;
    private javax.swing.JRadioButton scissors;
    private javax.swing.JLabel winner;
    // End of variables declaration//GEN-END:variables
}
